### ISSUE TITLE
Bug: False warning for property mismatch when using resolve_target_entities

### ISSUE THREAD

**Issue by CoalaJoe** [phpstan/phpstan-doctrine#121]
I get a lot of errors like these:
```
Property App\Entity\Example::$example  mapping mismatch: database can contain  App\Entity\OtherExample|null but property expects App\Contract\OtherExampleInterface.
```

In the doctrine configuration under `doctrine.orm`, you can configure mappings of Interfaces to entities. I basically have something like this:

```yaml
doctrine:
  # ...
  orm:
    # ...
    resolve_target_entities:
      App\Contract\OtherExampleInterface: App\Entity\OtherExample
```
