### ISSUE TITLE
Always-read and written properties

### ISSUE THREAD

**Issue by AnjaLiebermann** [phpstan/phpstan-doctrine#250]
I use doctrine and have a table/entity "RecipientType" , which is only read. The table provides an information used in another table/entity called "GroupRecipient".

I have installed 
```
        "phpstan/extension-installer":  "^1.1.0",
        "phpstan/phpstan":  "^1.4.2",
        "phpstan/phpstan-doctrine":  "^1.1.1"
```

and run a symfony5.4 on php 8.0.13

[see here](https://phpstan.org/r/6bbf5b30-20b7-4f5b-be6d-5d38426470a4)

When I run phpstan on level 5 I get the message:
```
 ------ ----------------------------------------------------------------------------------
  Line   src/Entity/RecipientType.php
 ------ ----------------------------------------------------------------------------------
  45     Property App\Entity\RecipientType::$groupRecipients is never written, only read.
         💡 See: https://phpstan.org/developing-extensions/always-read-written-properties
 ------ ----------------------------------------------------------------------------------
```

While this Url explains that this case should be coevred via the installed doctrine extension.
"Properties for Doctrine ORM are already covered by the official PHPStan extension. "

What is wrong?

**Comment by ondrejmirtes** [comment]
Follow the README regarding the objectManagerLoader: https://github.com/phpstan/phpstan-doctrine#configuration

**Comment by AnjaLiebermann** [comment]
I had that already in place:
```
parameters:
    doctrine:
        objectManagerLoader: tests/object-manager.php
    level: 5
    paths:
        - src/
        - tests/
    excludePaths:
        - %rootDir%/../../../migrations/*
        - %rootDir%/../../../src/Domain/Item/Event/AbstractItemEvent.php
        - %rootDir%/../../../tests/bootstrap.php
        - %rootDir%/../../../tests/object-manager.php
    checkGenericClassInNonGenericObjectType: false
    checkMissingIterableValueType: false
    inferPrivatePropertyTypeFromConstructor: true
    ignoreErrors:
    #   - '#Call to an undefined method [a-zA-Z0-9\\_]+::countByType\(\).#'
       - '/Call to an undefined method Doctrine\\Persistence\\ObjectRepository::count\(\)./'
       - '/If condition is always true./'
    #   - checkGenericClassInNonGenericObjectType: false
    #   - checkMissingIterableValueType: false
```

and I use the Symfony 5 Version of the objectmanager file, which makes no difference to the symfony 4 version in the end result:

```
<?php

use App\Kernel;
use Symfony\Component\Dotenv\Dotenv;

require __DIR__ . '/../vendor/autoload.php';

(new Dotenv())->bootEnv(__DIR__ . '/../.env');

$kernel = new Kernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);
$kernel->boot();

return $kernel->getContainer()->get('doctrine')->getManager();

```

"symfony/dotenv": "5.4.*", is installed as well. Did I miss something else?
