### ISSUE TITLE
The 'find', 'findBy*', 'findOneBy*' methods of ServiceEntityRepository are not recognized

### ISSUE THREAD

**Issue by jiti02** [phpstan/phpstan-doctrine#289]
When an entity is get via 'find' method of a ServiceEntityRepository the following errors appeared:
1) `Call to an undefined method object::getName()`.
This error appears when the getName method is called for that entity
E.g: 
      ```
      $product = $this->productRepository->find($productId);
      $product->getName();
      ```

2) `Parameter #1 $product of method processProduct() expects App\Entity\Product, object given.`  
This error appears when a method that expects to recive a Product as parameter is called.
E.g:
      ```
      public function processProduct(Product $product): void
      {}
      
      $product = $this->productRepository->find($productId);
      $this->processProduct($product)
      ```

3) Method getProduct should return App\Entity\Product but returns object.      	
This error appears when the $product is returned by a method that is expected to return an entity
E.g:
      ```
      public function getProduct(): Product 
      {
      return  $this->productRepository->find($productId);
      }
      ```

It seams that the 'find', 'findBy*', 'findOneBy*' methods of ServiceEntityRepository are not recognized.
Please note that the PhpStan version 1.4.6 and phpstan-doctrine version 1.2.8 were used.

The following phpstan.neon file is used:
```
parameters:
    level: 9
    paths:
        - src
    scanFiles:
        - tests/_support/_generated/AcceptanceTesterActions.php
        - tests/_support/_generated/FunctionalTesterActions.php
        - tests/_support/_generated/IntegrationTesterActions.php
        - tests/_support/_generated/UnitTesterActions.php
    checkMissingIterableValueType: false
    checkGenericClassInNonGenericObjectType: false
    doctrine:
            objectManagerLoader: tests/object-manager.php
    symfony:
        container_xml_path: '%rootDir%/../../../var/cache/dev/App_KernelDevDebugContainer.xml'
        console_application_loader: tests/console-application.php
    bootstrapFiles:
        - tests/_support/_generated/AcceptanceTesterActions.php
        - tests/_support/_generated/FunctionalTesterActions.php
        - tests/_support/_generated/IntegrationTesterActions.php
        - tests/_support/_generated/UnitTesterActions.php
```

The following 'object-manager.php' is used:
```
use App\Kernel;
use Symfony\Component\Dotenv\Dotenv;

require __DIR__ . '/../vendor/autoload.php';

(new Dotenv())->bootEnv(__DIR__ . '/../.env');

$kernel = new Kernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);
$kernel->boot();

return $kernel->getContainer()->get('doctrine')->getManager();
```
