### ISSUE TITLE
Error with DoctrineBundle

### ISSUE THREAD

**Issue by craigh** [phpstan/phpstan-doctrine#411]
I'm getting the error below. I'd appreciate any help.

> Note: Using configuration file /path/to/phpstan.neon.
PHP Fatal error:  Trait "Symfony\Component\VarExporter\LazyGhostTrait" not found in /myproject/vendor/doctrine/doctrine-bundle/Repository/LazyServiceEntityRepository.php on line 31
Fatal error: Trait "Symfony\Component\VarExporter\LazyGhostTrait" not found in /myproject/vendor/doctrine/doctrine-bundle/Repository/LazyServiceEntityRepository.php on line 31
make: *** [stan] Error 255

refs #409  and refs https://github.com/doctrine/DoctrineBundle/issues/1614

I am using
 - Symfony 5.4.18
 - DoctrineBundle 2.8.2
 - phpstan/phpstan 1.9.7
 - phpstan/phpstan-doctrine 1.3.30
 - phpstan/extension-installer 1.2.0

```
# phpstan.neon.dist
parameters:
    paths:
        - src
    level: 3
    scanFiles:
        - vendor/twig/twig/src/Extension/EscaperExtension.php
    ignoreErrors:
        - '#Call to an undefined method Symfony\\Component\\Console\\Helper\\HelperInterface::ask\(\).#'
```

I'm not 100% certain I have `phpstan/phpstan-doctrine` configured correctly so the problem could be on my end. As you can see, I am using `phpstan/extension-installer` and the docs say "If you also install phpstan/extension-installer then you're all set!". Perhaps I should have something more?
