### ISSUE TITLE
False-negative allows to return any Collection.

### ISSUE THREAD

**Issue by biozshock** [phpstan/phpstan-doctrine#434]
The code below does not show any errors. 
However if you copy all classes to the playground the error is detected. https://phpstan.org/r/4529cd8b-36d6-459d-b737-8fe3c48936f0

```php

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

class Foo{}

class Bar {
	
	/** @var Collection<int, Foo> */
	private Collection $collection;
	
	public function __construct()
	{
		$this->collection = new ArrayCollection();
	}
	
	/**
	 * @return Collection<int, Foo>
	 */
	function get(): Collection
	{
		$col = new ArrayCollection();
		$col->add(new \stdClass);

		return $col;
	}
}
```

Thanks for making PHPStan!

**Comment by ondrejmirtes** [comment]
So what’s your expectation? Do you expect your application to also report this error but it currently doesn’t when analyzed? This is kind of missing from your description.

Can you share your config and how you run PHPStan on the command line?

**Comment by biozshock** [comment]
Oh, sorry. Missed that part.

Yes, i think PHPStan should report something like `Method Bar::get() should return Collection<int, Foo> but returns ArrayCollection<int, stdClass>.`.

The config is simple:
```
includes:
	- vendor/phpstan/phpstan-deprecation-rules/rules.neon
	- vendor/phpstan/phpstan-strict-rules/rules.neon
	- vendor/phpstan/phpstan-symfony/extension.neon
	- vendor/phpstan/phpstan-symfony/rules.neon
	- vendor/phpstan/phpstan-doctrine/extension.neon
	- vendor/phpstan/phpstan-doctrine/rules.neon

parameters:
    level: max
    treatPhpDocTypesAsCertain: false
    tmpDir: var/cache/dev
    symfony:
        container_xml_path: var/cache/dev/App_KernelDevDebugContainer.xml
        console_application_loader: config/phpstan/console-loader.php
    doctrine:
        repositoryClass: App\Repository\AbstractRepository
        objectManagerLoader: config/phpstan/doctrine-orm-bootstrap.php
``` 

console-loader.php:
```php
<?php declare(strict_types = 1);

use App\Kernel;
use Symfony\Bundle\FrameworkBundle\Console\Application;

require dirname(__DIR__) . '/bootstrap.php';
$kernel = new Kernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);
return new Application($kernel);
```

doctrine-orm-bootstrap.php
```php
<?php declare(strict_types = 1);

use App\Kernel;

require dirname(__DIR__) . '/bootstrap.php';
$kernel = new Kernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);
$kernel->boot();
return $kernel->getContainer()->get('doctrine')->getManager();
```

Command: `phpstan analyse -c phpstan.neon src -l max --memory-limit=1G`, where `phpstan` is a link to `vendor/bin/phpstan`
