### ISSUE TITLE
Invalid finding: Auto-Generated ID is never assigned int 

### ISSUE THREAD

**Issue by kevinpapst** [phpstan/phpstan-doctrine#610]
Expected:
PHPStand understands that such a definition is valid and that $id is set to `int` by Doctrine.

Actual:
> Property HelloWorld::$id (int|null) is never assigned int so it can be removed from the property type.

```php
    #[ORM\Column(name: 'id', type: 'integer')]
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'IDENTITY')]
    private ?int $id = null;

    public function __clone()
    {
        if ($this->id !== null) {
            $this->id = null;
        }
        // ...
     }
}
```

Only happens when I have that clone method in place, which says that id is not null 😁 

Playground: https://phpstan.org/r/ed1ce389-72ab-4deb-a1bc-6d570db17f87 
But in that case it makes sense, as there is no Doctrine annotation/bridge available.

**Comment by scannerGT** [comment]
I have the same issue. Entity generatet via maker, id is nullable and autogenerated, PHPStan 2.0.2 (lvl 6). Nop setter, no __clone - just pure Symfony entity and fresh PHPStan installation.

**Comment by kevinpapst** [comment]
To share some more infos: this does not generally happen. Only in one Symfony bundle of at least 6 of my bundles that use Doctrine entities. I invested a few hours to find a reason and/or fix, but nothing worked. 
This is my PHPStan and work-around:

```
includes:
  - %rootDir%/../phpstan-symfony/extension.neon
  - %rootDir%/../phpstan-symfony/rules.neon
  - %rootDir%/../phpstan-doctrine/extension.neon
  - %rootDir%/../phpstan-doctrine/rules.neon
  - %rootDir%/../phpstan-deprecation-rules/rules.neon
  - %rootDir%/../phpstan-strict-rules/rules.neon
  - %rootDir%/../phpstan/conf/bleedingEdge.neon

parameters:
  level: 9
  excludePaths:
    - vendor/(?)
  scanDirectories:
    - Migrations
  treatPhpDocTypesAsCertain: false
  inferPrivatePropertyTypeFromConstructor: true
  doctrine:
    allowNullablePropertyForRequiredField: true
  ignoreErrors:
    -
      message: "#^Property App\\\\Entity\\\\HelloWorld\\:\\:\\$id \\(int\\|null\\) is never assigned int so it can be removed from the property type\\.$#"
      reportUnmatched: false
      path: Entity/Task.php
```

**Comment by DennisdeBest** [comment]
Hello, I had the same issue. To ignore it for all the entities I added :
```
       - '#Property .+::\$id \(int\|null\) is never assigned int so it can be removed from the property type\.$#'
```

To the ignoreErrors.

**Comment by GuillaumeVrill** [comment]
I confirm the following workaround works (file `phpstan.dist.neon`) : 

```
parameters:
    ...
    ignoreErrors:
        - message: "#^Property App\\\\Entity\\\\.*\\:\\:\\$id \\(int\\|null\\) is never assigned int so it can be removed from the property type\\.$#"
```

I reproduce on a recent project, with standard configuration, on basic entities **with or without the clone method**. 

Code example on a basic doctrine entity : 

```
#[ORM\Entity(repositoryClass: MyEntity::class)]
class MyEntity
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;
    
    public function getId(): ?int
    {
        return $this->id;
    }
    
    // No setter, as it's autogenerated / managed by Doctrine. 
}

```

If you do not wish (or can't, for any reason) edit your `phpstan.dist.neon` file, adding a setter like the following resolves the problem, but i don't know if that could conflict with Doctrine native behavior (though i don't think so). 

```
public function setId(int $id): self
{
    $this->id = $id;

    return $this;
}
```
